# Corpus opts:
data:
    train:
        path_src: /scratch/project_2001403/arbruiser/project/model1/MultiUN/Transformer/Data/BPE/train.bpe.ru
        path_tgt: /scratch/project_2001403/arbruiser/project/model1/MultiUN/Transformer/Data/BPE/train.bpe.en
    valid:
        path_src: /scratch/project_2001403/arbruiser/project/model1/MultiUN/Transformer/Data/BPE/val.bpe.en
        path_tgt: /scratch/project_2001403/arbruiser/project/model1/MultiUN/Transformer/Data/BPE/val.bpe.ru

# Where the vocab(s) will be written
src_vocab: /scratch/project_2001403/arbruiser/project/model1/MultiUN/Transformer/vocab.ru_en.src
tgt_vocab: /scratch/project_2001403/arbruiser/project/model1/MultiUN/Transformer/vocab.ru_en.tgt

save_model: ./transformer_ru_en
train_steps: 200000
save_checkpoint_steps: 40000
keep_checkpoint: 2
valid_steps: 10000
world_size: 1
gpu_ranks: [0]
seed: 3435
warmup_steps: 8000
report_every: 1000

decoder_type: transformer
encoder_type: transformer
word_vec_size: 1024
hidden_size: 1024
layers: 9
transformer_ff: 2048
heads: 8

accum_count: 2
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0

batch_size: 4096
batch_type: tokens
normalization: tokens
dropout: 0.1
label_smoothing: 0.1

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

